databases:
  - name: cosplay-angola-db
    databaseName: cosplay_angola
    user: cosplay_angola
    plan: free

services:
  - type: web
    name: cosplay-angola-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: cosplay-angola-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://seu-frontend.vercel.app,https://seu-frontend.netlify.app
